server:
  port: 10000

spring:
  datasource:
    url: jdbc:mysql://192.168.1.101:3306/tetto?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 192.168.1.101
    password: xxxx
    database: 0
    timeout: 10000
  cache:
    type: redis
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: -1
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

ai:
  api:
    proxy-enable: false
    proxy-host: "127.0.0.1"
    proxy-port: 80
    host: "http://localhost:90"
    file-path: "D:\\images"
    file-name-date-format: "yyyy-MM-dd"
    finish-task-map-size: 100

  auth:
    secret: qewgtewehewhehfshsgfhsea
    # 有效期，单位分钟 默认60分钟
    expiration: 1440
    captcha-enabled: false
    captcha-host: "https://challenges.cloudflare.com"
    captcha-path: "/turnstile/v0/siteverify"
    captcha-secret-key: "0xxxxx"
    hostname: "test.com"
    default-avatar: "https://test.com/avatar.jpg"

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
